/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package lox

import spock.lang.Specification

class LoxTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new Lox()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
